# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  prayertimesapi:
    image: prayertimesapi
    build:
      context: .
      dockerfile: PrayerTimes.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
